# Generated by Django 5.2.7 on 2025-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='input_language',
            field=models.CharField(choices=[('af', 'afrikaans'), ('sq', 'albanian'), ('am', 'amharic'), ('ar', 'arabic')], default='af', max_length=100),
        ),
    ]
