# Generated by Django 5.2.7 on 2025-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_card_input_language_alter_card_output_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('result', models.TextField(max_length=250)),
            ],
        ),
    ]
