# Generated by Django 5.2.7 on 2025-10-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_resultcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultcard',
            name='note',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='resultcard',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
