# Generated by Django 5.2.7 on 2025-10-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_resultcard_note_alter_resultcard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcard',
            name='title',
            field=models.TextField(default='ES->EN', max_length=100),
        ),
    ]
