# Generated by Django 5.2.7 on 2025-10-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_resultcard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultcard',
            name='note',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='resultcard',
            name='title',
            field=models.CharField(default='ES->EN', max_length=20),
        ),
    ]
