# Generated by Django 5.2.7 on 2025-10-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_card_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('textnote', models.CharField(max_length=100)),
                ('resultcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.resultcard')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
